name: CI/CD Pipeline  # Nome do workflow

on:
  push:
    branches:
      - main  # Gatilho: qualquer push para a branch "main"

jobs:
  build:
    runs-on: ubuntu-latest  #Ambiente em que o trabalho será executado

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2  # Ação para fazer checkout do repositório

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1  # Configura o Docker para builds multiplataforma

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário do Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Senha do Docker Hub

      - name: Construir e enviar a imagem Docker
        uses: docker/build-push-action@v2
        with:
          context: .  # Diretório atual como contexto do Docker
          push: true  # Enviar a imagem para o Docker Hub
          tags: yourusername/yourimage:latest  # Substituir com seu usuário e imagem